spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 0000
    url: jdbc:postgresql://localhost:5432/bookstore
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

jwt_secret: ${JWT_SECRET:erklytgvbnelwruyghulrtnhgnlurethu}

